id: P000239
initial_creation_type: ebook
source_metadata:
  title: ༄༅། །ལེགས་བཤད་ཉི་མ་རང་ཤར་ཞེས་བྱ་བ་བཞུགས་སོ། །
  authors:
  - མཛད་པ་པོ། ཞབས་དཀར་ཚོགས་དྲུག་རང་གྲོལ།
  layers:
  - book_title
  - author
  - quotation
  - yigchung
  id: SHE-SHAP-15
web_metadata:
  title:
    en: The Self-Arising Sun:An Excellent Discourse
    bo: ལེགས་བཤད་ཉི་མ་རང་ཤར་ཞེས་བྱ་བ་བཞུགས་སོ།
  collection:
    en: Shabkar Series–  Book 15
    bo: ཞབས་དཀར་གསུང་འབུམ།–  དེབ། ༡༥
  author:
    en: Shabkar Tsokdruk Rangdrol
    bo: ཞབས་དཀར་ཚོགས་དྲུག་རང་གྲོལ།
  pusblisher:
    en: Shechen Publications
    bo: ཞེ་ཆེན་བསྟན་གཉིས་དར་རྒྱས་གླིང།
  sku: SHE-SHAP-15
  category:
    en: Dharma Teaching
    bo: ཆོས་བསླབ་བྱ།
  org:
    bo: Timeless Treasuries
    en: མཐའ་ཡས་དཔེ་མཛོད།
  website: http://dharmacloud.tsadra.org
  aquisition_data: '2019-07-18'
  filename: SHE-SHAP-15.epub
  description:
    en: ''
    bo: ''
